require 'socket'

tap 'caskroom/cask'
tap 'neovim/neovim'

brew 'aspell'
brew 'awscli'
brew 'cmake'
brew 'findutils'
brew 'fzf'
brew 'git'
brew 'gnu-tar'
brew 'httpie'
brew 'jq'
brew 'markdown'
brew 'neovim'
brew 'openssl'
brew 'p7zip'
brew 'parallel'
brew 'python'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'rsync'
brew 'ruby-build'
brew 'sloccount'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'unrar'
brew 'watch'
brew 'wget'
brew 'xz'
brew 'zplug'
brew 'zsh'

cask 'anki'
cask 'colorpicker'
cask 'colorpicker-hex'
cask 'firefox'
cask 'franz'
cask 'istat-menus'
cask 'iterm2'
cask 'kindle'
cask 'keepingyouawake'
cask 'skitch'
cask 'spectacle'
cask 'spotify'

case Socket.gethostname
when /seldon/i
  cask 'arq'
  cask 'cleanmymac'
  cask 'docker'
end

# vim: filetype=ruby
