tap 'caskroom/cask'

brew 'findutils'
brew 'fzf'
brew 'git'
brew 'gnu-tar'
brew 'httpie'
brew 'openssl'
brew 'p7zip'
brew 'reattach-to-user-namespace'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'unrar'
brew 'watch'
brew 'wget'
brew 'xz'

cask 'anki'
cask 'colorpicker'
cask 'colorpicker-hex'
cask 'keepingyouawake'
cask 'skitch'
cask 'spotify'

# vim: filetype=ruby
